/**
 * Copyright (c) Qorg, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  courses: [
    {
      type: 'autogenerated',
      dirName: 'courses/jc-1',
    },
  ],
  intro: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'introduction',
    },
  ],
  manu: [
    {
      type: 'autogenerated',
      dirName: 'manu',
    },
  ],
  // But you can create a sidebar manually
}

const sidebars1 = {
  courses: [
    {
      type: 'autogenerated',
      dirName: 'courses/jc-1',
    },
  ],
  intro: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'introduction',
    },
  ],
  manu: [
    {
      type: 'autogenerated',
      dirName: 'manu',
    },
  ],
  // But you can create a sidebar manually
}

//console.log(sidebars, sidebars1, sidebars === sidebars1)
module.exports = sidebars1